### ISSUE TITLE
无障碍点击控件报错

### ISSUE THREAD

**Issue by wangwang-code** [openautojs/openautojs#6]
1. Autox.js 版本：643
2. Autox.js 下载渠道：自编译https://github.com/wangwang-code/openautojs/releases
3. Android 版本：Android 7
4. Android 机型：vmos
5. Android 系统类别：vmos
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：打包的项目在vmos中运行，尝试点击控件，发生错误。物理机已验证正常运行
8. 报错日志（可选）：
<details><summary>日志(巨多)</summary>

<p>

Thread[ScriptThread-1[/data/user/0/ww.autoxjs.study/files/project/Study.js] (Spawn-2),5]: android.view.accessibility.AccessibilityNodeInfo$ExtraRenderingInfo

java.lang.NoClassDefFoundError: android.view.accessibility.AccessibilityNodeInfo$ExtraRenderingInfo
	at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
	at java.lang.Class.getDexCacheType(Class.java:2551)
	at java.lang.reflect.Method.getReturnType(Method.java:150)
	at org.mozilla.javascript.JavaMembers.extractGetMethod(JavaMembers.java:697)
	at org.mozilla.javascript.JavaMembers.findGetter(JavaMembers.java:684)
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:576)
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:54)
	at org.mozilla.javascript.JavaMembers.createJavaMembers(JavaMembers.java:827)
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:786)
	at org.mozilla.javascript.NativeJavaObject.initMembers(NativeJavaObject.java:63)
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:53)
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:44)
	at org.mozilla.javascript.WrapFactory.wrapAsJavaObject(WrapFactory.java:120)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine$WrapFactory.wrapAsJavaObject(RhinoJavaScriptEngine.kt:167)
	at org.mozilla.javascript.WrapFactory.wrap(WrapFactory.java:74)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine$WrapFactory.wrap(RhinoJavaScriptEngine.kt:158)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:227)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1879)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:88)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:171)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invokeImpl(VMBridge_custom.java:149)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.lambda$invoke$0$org-mozilla-javascript-VMBridge_custom$InterfaceAdapterWrapper(VMBridge_custom.java:131)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.call(VMBridge_custom.java:140)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invoke(VMBridge_custom.java:132)
	at org.mozilla.javascript.VMBridge_custom.lambda$newInterfaceProxy$0$org-mozilla-javascript-VMBridge_custom(VMBridge_custom.java:65)
	at org.mozilla.javascript.VMBridge_custom$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass)
	at java.lang.reflect.Proxy.invoke(Proxy.java:813)
	at $Proxy5.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at com.stardust.autojs.core.looper.TimerThread.run(TimerThread.java:46)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.accessibility.AccessibilityNodeInfo$ExtraRenderingInfo" on path: DexPathList[[zip file "/data/app/ww.autoxjs.study-1/base.apk"],nativeLibraryDirectories=[/data/app/ww.autoxjs.study-1/lib/arm64, /data/app/ww.autoxjs.study-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
	at java.lang.Class.getDexCacheType(Class.java:2551)
	at java.lang.reflect.Method.getReturnType(Method.java:150)
	at org.mozilla.javascript.JavaMembers.extractGetMethod(JavaMembers.java:697)
	at org.mozilla.javascript.JavaMembers.findGetter(JavaMembers.java:684)
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:576)
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:54)
	at org.mozilla.javascript.JavaMembers.createJavaMembers(JavaMembers.java:827)
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:786)
	at org.mozilla.javascript.NativeJavaObject.initMembers(NativeJavaObject.java:63)
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:53)
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:44)
	at org.mozilla.javascript.WrapFactory.wrapAsJavaObject(WrapFactory.java:120)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine$WrapFactory.wrapAsJavaObject(RhinoJavaScriptEngine.kt:167)
	at org.mozilla.javascript.WrapFactory.wrap(WrapFactory.java:74)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine$WrapFactory.wrap(RhinoJavaScriptEngine.kt:158)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:227)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1879)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:88)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:171)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invokeImpl(VMBridge_custom.java:149)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.lambda$invoke$0$org-mozilla-javascript-VMBridge_custom$InterfaceAdapterWrapper(VMBridge_custom.java:131)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.call(VMBridge_custom.java:140)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invoke(VMBridge_custom.java:132)
	at org.mozilla.javascript.VMBridge_custom.lambda$newInterfaceProxy$0$org-mozilla-javascript-VMBridge_custom(VMBridge_custom.java:65)
	at org.mozilla.javascript.VMBridge_custom$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass)
	at java.lang.reflect.Proxy.invoke(Proxy.java:813)
	at $Proxy5.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at com.stardust.autojs.core.looper.TimerThread.run(TimerThread.java:46) 

</p>
</details>

**Comment by wangwang-code** [comment]
chatGPT:
这个报错是一个类找不到的错误，具体地说就是无法找到 android.view.accessibility.AccessibilityNodeInfo$ExtraRenderingInfo 这个类。这个类可能是在某个库中定义的，但是在运行时它没有被加载进来，导致程序运行出错。

对于这种问题，一般可以考虑以下几点：

查看你的项目依赖是否有问题，比如你缺少了某些库或者依赖版本不对等等。
检查你的代码中是否有引用该类的部分，看看是否出现了拼写错误等问题。
确认你的设备上是否缺少相关的系统组件或者配置，导致该类无法找到。
希望这能帮到你！

我需要些时间验证，是只编译64位引起的

**Comment by wangwang-code** [comment]
已排除 使用双平台依赖打包仍然报错

**Comment by wilinz** [comment]
我也遇到这个问题，经测试，似乎是 Android 版本的问题，Android 9 以下会出现这个问题

**Comment by wangwang-code** [comment]
> 我也遇到这个问题，经测试，似乎是 Android 版本的问题，Android 9 以下会出现这个问题

这个问题不必在研究下去了
另外我知道为什么vivo的原系统在给了 **允许管理所有文件** 的权限后创建文件**看不到的问题**，是**原子隐私系统造**成的

**Comment by LZX284** [comment]
后记：确实是遇到灵异事件了，除了[之前提到的](https://github.com/wangwang-code/AutoX/issues/52#issuecomment-1464892480)，后来甚至还被搞得进了医院，起因应该是之前autoxjs的争论事件，造成伤害的源头可能是一种灵体（和”阿飘“类似），能对人的精神产生影响，曾经尝试和灵体沟通解决，没有结果，只有一些目前能够确认的信息，比如名字是”程书伦“。那一段时间简直和噩梦一样，不想再经历类似痛苦的事件了，说出来只是防止如果有人再次遇到时能有个参考吧
